@extends('layouts.app')

@section('title', 'À propos')

@section('content')
<div class="container single about">
        <div class="single__complementary-block  ta-j">
            <h1 class="single__complementary-block-title">À propos</h1>
            <p>Depuis 25 ans, Le <b>Lien MULTIMÉDIA</b> offre une couverture journalistique dont l’unique but est de servir une communauté effervescente de créateurs, visionnaires et entrepreneurs en culture numérique.  Le portail des professionnels du numérique au Québec, <a href="http://www.lienmultimedia.com">www.lienmultimedia.com</a>, et son application mobile iOS et Androïd contiennent plus de 75 750 articles et 1350 entrevues vidéos et podcasts avec des artisans et décideurs du milieu.  Le <b>Lien MULTIMÉDIA</b> produit également des livres, rapports de veilles et d'intelligence d'affaires, des contenus thématiques sur la réalité virtuelle, les webséries, l’intelligence artificielle, l’apprentissage en ligne, les arts numériques, les jeux vidéo, l’écriture interactive, entre autres. Le <b>Lien MULTIMÉDIA</b> publie <b>CONVERGENCE</b>, le magazine de la culture et de l’entreprise numérique au Québec, refuge des articles de fond, des analyses inspirées et des interviews au long cours.</p>
            <p>Le <b>Lien MULTIMÉDIA</b> exploite le potentiel de différentes plateformes et expérimente plusieurs modèles d'affaires: un site Web en libre accès dont les nouvelles sont aussi accessibles en format plus détaillé pour ses <a href="http://www.lienmultimedia.com/boutique">abonnés</a>, une infolettre hebdomadaire par abonnement payant, une infolettre quotidienne gratuite et un magazine numérique disponible en format PDF et flipbook, <a href="http://www.lienmultimedia.com/convergence"><b>CONVERGENCE</b></a> et finalement, une application mobile iOS et Androïd.</p>
            <p><b>La COLLECTION NUMÉRIQUE</b> est une plateforme Web responsive qui répertorie les productions québécoises en jeu vidéo, arts numériques et immersifs, réalité virtuelle, animation et applications mobiles culturelles, entre autres. Alimentée par l'équipe du <b>Lien MULTIMÉDIA</b> et aussi par le public et les créateurs, <b>La COLLECTION NUMÉRIQUE</b>, c'est surtout un lieu d'échanges, où la communauté peut interagir et suivre l'actualité de ce qui est fait ici. En quelques clics, l'utilisateur peut renseigner la fiche d'une production qu'il connaît, consulter les fiches des productions qui l'intéressent, découvrir les créateurs des oeuvres numériques directement dans <b>La COLLECTION NUMÉRIQUE</b> !</p>
            <p><b>La COLLECTION NUMÉRIQUE</b> n'est pas une collection comme les autres. Son but est d'offrir une plateforme et une expérience complète pour une diversité de public : l'invité amateur qui est juste curieux, la passionnée qui veut partager ses coups de coeur à ses amis, le chercheur qui a une idée en tête, la créatrice qui souhaite faire partager sa production ou encore le curieux qui cherche à découvrir des productions d'ici. En créant un véritable lieu d'expression pour les productions numériques québécoises et ceux qui les aiment, nous facilitons la découvrabilités des oeuvres québécoises en numérique et souhaitons ouvrir les portes d'un musée populaire et accessible.</p>
            <p>Le <b>Lien MULTIMÉDIA</b> fournit des informations stratégiques et pratiques sur l’industrie du numérique (médias numériques, réalité virtuelle, intelligence artificielle, jeux vidéo, affaires électroniques, contenus numériques, applications mobiles, développement Web, affichage électronique, animation, arts médiatiques...), de l’audiovisuel et des technologies de l’information. Par conséquent, il cible les professionnels oeuvrant dans ces industries émergentes. La publication couvrant un large éventail de sujets, son lectorat s'en trouve diversifié: entrepreneurs, dirigeants d'organismes et d'associations, fournisseurs de services, enseignants, étudiants, artistes, techniciens, avocats d'affaires, créateurs de jeux vidéo, cadres, responsables de ressources humaines, spécialistes du marketing, agences...</p>
        </div>
</div>
@endsection